setup.sh script to get canvas-lms repo working easily
bebraven/canvas-lms pull request #31
Opened 2020-10-21 00:44 UTC by hcli-work

https://app.asana.com/0/1179330853755533/1198870084975605

Just a small script that builds, launches, refreshes database for Canvas repo

Test Plan: used it and then tried accessing via canvasweb:3000

2020-10-26 15:51 UTC, hcli-work commented
this is not ready for review yet. found a little hitch that I need to fix.

2020-10-27 17:53 UTC, hcli-work commented
ready now

2020-10-27 22:47 UTC, sadleb requested changes
Many of my comments from the equivalent platform PR apply, but the big one is adding the db dumps (both binary and SQL) to .dockerignore. The other repos use heroku build packs and the docker containers are only for dev, but this repo uses the docker images to build production so it’s important we don’t build things like the whole production database, into the images. It’ll blow the image sizes up by at least 6GB in addition to the obvious security implications. In fact, one of the reasons that I had db refreshes run off production snapshots that had already been sanitized to work in staging by the admin server cron job was because I didn’t want to let devs access real production DBs directly on their local machines. That’s a SysOps security no-no.

2020-10-30 13:51 UTC, hcli-work commented
I think I'm missing something here about the security point. The approach I've been going with has been to download the snapshot and then restore it. The current approach is to do the same thing with the main differences being that the download came from S3 and the dump itself wasn't saved on disk. But the data itself was persisted into the db containers, which ends up just writing it on disk anyway.

2020-12-01 16:17 UTC, sadleb requested changes

2020-12-01 16:17 UTC, sadleb commented on docker-compose/scripts/db_gensqldump.sh
> +docker-compose exec canvasdb pg_restore --clean --jobs 2 --no-acl --no-owner -U canvas -d canvas latest.dump
You cleaned this up in one of the related PRs. Is this still a mistake or do we really need to run the restore twice? Also, is `latest.dump` the default file name that running the Heroku download goes into? It's confusing why `db_gensqldump.sh` starts with a restore. Either comment why or rename the script to be more appropriate? From what I can gather, this is just migrating the latest dump to a dev DB?

2020-12-01 16:17 UTC, sadleb commented on docker-compose/scripts/db_gensqldump.sh
> +docker-compose exec canvasdb pg_dump --clean -U canvas canvas > latest-tmp.sql
Future readers aren't going to understand what is going on here at first glance. This is necessary b/c the Heroku dump is a binary dump and we need to turn it into a .sql dump, correct? If so maybe just clarify the above echo to be something like "Migrating binary database snapshot to SQL snapshot"?

2020-12-01 16:17 UTC, sadleb commented on docker-compose/scripts/db_gensqldump.sh
> +echo "Replacing production URLs with dev URLs...piping to database"
You're not piping it to the database from what I can tell.

2020-12-03 22:15 UTC, hcli-work commented on docker-compose/scripts/db_gensqldump.sh
> +docker-compose exec canvasdb pg_restore --clean --jobs 2 --no-acl --no-owner -U canvas -d canvas latest.dump
good catch. you're right. i cleaned it up in the actual restore. this is here just to convert the binary dump into a SQL one. i'll clean up here as well and then add some comments as to why it's needed.

2020-12-03 22:15 UTC, hcli-work commented on docker-compose/scripts/db_gensqldump.sh
> +docker-compose exec canvasdb pg_dump --clean -U canvas canvas > latest-tmp.sql
+1

2020-12-03 22:15 UTC, hcli-work commented on docker-compose/scripts/db_gensqldump.sh
> +echo "Replacing production URLs with dev URLs...piping to database"
+1

2020-12-07 14:47 UTC, sadleb approved these changes
lgtm

2020-12-08 01:50 UTC, merged